/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsTafelbergFurnishersRouteImport } from './routes/projects.tafelberg-furnishers'
import { Route as ProjectsBedsOnLineRouteImport } from './routes/projects.beds-on-line'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsTafelbergFurnishersRoute =
  ProjectsTafelbergFurnishersRouteImport.update({
    id: '/tafelberg-furnishers',
    path: '/tafelberg-furnishers',
    getParentRoute: () => ProjectsRoute,
  } as any)
const ProjectsBedsOnLineRoute = ProjectsBedsOnLineRouteImport.update({
  id: '/beds-on-line',
  path: '/beds-on-line',
  getParentRoute: () => ProjectsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/work': typeof WorkRoute
  '/projects/beds-on-line': typeof ProjectsBedsOnLineRoute
  '/projects/tafelberg-furnishers': typeof ProjectsTafelbergFurnishersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/work': typeof WorkRoute
  '/projects/beds-on-line': typeof ProjectsBedsOnLineRoute
  '/projects/tafelberg-furnishers': typeof ProjectsTafelbergFurnishersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/work': typeof WorkRoute
  '/projects/beds-on-line': typeof ProjectsBedsOnLineRoute
  '/projects/tafelberg-furnishers': typeof ProjectsTafelbergFurnishersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/projects'
    | '/work'
    | '/projects/beds-on-line'
    | '/projects/tafelberg-furnishers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/projects'
    | '/work'
    | '/projects/beds-on-line'
    | '/projects/tafelberg-furnishers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/gallery'
    | '/projects'
    | '/work'
    | '/projects/beds-on-line'
    | '/projects/tafelberg-furnishers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  WorkRoute: typeof WorkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/tafelberg-furnishers': {
      id: '/projects/tafelberg-furnishers'
      path: '/tafelberg-furnishers'
      fullPath: '/projects/tafelberg-furnishers'
      preLoaderRoute: typeof ProjectsTafelbergFurnishersRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/beds-on-line': {
      id: '/projects/beds-on-line'
      path: '/beds-on-line'
      fullPath: '/projects/beds-on-line'
      preLoaderRoute: typeof ProjectsBedsOnLineRouteImport
      parentRoute: typeof ProjectsRoute
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsBedsOnLineRoute: typeof ProjectsBedsOnLineRoute
  ProjectsTafelbergFurnishersRoute: typeof ProjectsTafelbergFurnishersRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsBedsOnLineRoute: ProjectsBedsOnLineRoute,
  ProjectsTafelbergFurnishersRoute: ProjectsTafelbergFurnishersRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  WorkRoute: WorkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
